version: '3'
services:
  nest-app:
    build: .
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
      - GOOGLE_SPREADSHEET_ID=your_spreadsheet_id
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=your_service_account_email
      - GOOGLE_PRIVATE_KEY=your_private_key
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          memory: 512M
