version: '3'
services:
  nest-app:
    build: .
    ports:
      - '3333:3333'
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NODE_OPTIONS=${NODE_OPTIONS}
    deploy:
      resources:
        limits:
          memory: 512M
